### ISSUE TITLE
Main Page- Stocks

### ISSUE THREAD

**Issue by jlightheart24** [Utah-Coding-Bootcamp-Project-1/stock-tracker#3]
My Stocks sections
 -using local storage, add a tracker for the users stocks

**Comment by BradCassityDev** [comment]
renderSavedStocks function is set up and ready to go. Just need to include on page load. We need default text to appear when it there are no stocks.

**Comment by BradCassityDev** [comment]
Rendering stocks on load. Ability to add stocks has been added as well.
