### ISSUE TITLE
Modal

### ISSUE THREAD

**Issue by jlightheart24** [Utah-Coding-Bootcamp-Project-1/stock-tracker#4]
When a stock is searched a modal shows.

**Comment by BradCassityDev** [comment]
Here is Foundations documentation on modals: https://get.foundation/sites/docs-v5/components/reveal.html
Thought this would help!

**Comment by BradCassityDev** [comment]
Scratch the foundation link and use this instead: https://semantic-ui.com/modules/modal.html

**Comment by BradCassityDev** [comment]
Need ability to exit modal.
