### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by BradCassityDev** [Utah-Coding-Bootcamp-Project-1/stock-tracker#8]
We need to handle some errors for a better user experience. 

Known errors include: 

- Search ticker not found
- out of requests from news api
- too many requests per minute with free account at finnhub.io
- Other errors in fetches to api endpoints. 

Display message to user on the page sot that they know to try again or deal with the error.

**Comment by jlightheart24** [comment]
added error messages for all these errors
